### PR TITLE
Update Operator-SDK and dependencies version

### LINKED ISSUE #446: Upgrade operator-sdk version and dependencies
Update the version of operator-sdk used by RCO first and then OLO and WLO

The operator-sdk version can only be updated one at a time (there is no way to jump to the latest version). Process is documented here: https://sdk.operatorframework.io/docs/upgrading-sdk-version/

### PR DESCRIPTION
**Pull request by halim-lee**
**What this PR does / why we need it?**:

- Updates Operator-sdk version to 1.24.0 and dependencies
- Kubernetes APIs to 0.24.2 (v1.24)
- Go to 1.19

**Does this PR introduce a user-facing change?**

- [ ] User guide
- [ ] `CHANGELOG.md`

**Which issue(s) this PR fixes**:

Fixes #446

### CODE REVIEW

**Comment by halim-lee** [comment]
Tests passed in RCO's ci-pipeline PipelineRun 269
For env configuration, Fyre cluster was set to mine and Go version set to 1.19.5

**Comment by halim-lee** [comment]
Updated APIs:
- prometheus operator to v0.57.0 (https://github.com/prometheus-operator/prometheus-operator/blob/v0.57.0/go.mod#L36) *uses k8s API v0.24.1 - next release uses v0.24.3
- cert manager to v1.9.2 (https://github.com/cert-manager/cert-manager/blob/v1.9.2/go.mod#L42) *uses k8s API v0.24.2
- knative serving to v0.34.4 (https://github.com/knative/serving/blob/v0.34.4/go.mod#L31) *uses k8s API v0.23.9 - next release uses v0.25.2

**Comment by halim-lee** [comment]
Tests passed with dep update changes in PipelineRun 272
For env configuration, Fyre cluster was set to mine and Go version set to 1.19.5

**Review by arturdzm — APPROVED** [review]

**Review by leochr — APPROVED** [review]
@halim-lee Thanks for the PR. Looks good to me.

**Pull request merged**
