### PR TITLE
Kustomise files for daily

### PR DESCRIPTION
**Pull request by idlewis**
start to deal with #177

### CODE REVIEW

**Review by leochr — COMMENTED** [review]
@idlewis Thanks. Looks good. Just want to confirm the purpose of _all-namespaces2_. Is it to specify a different namespace? Wondering whether changing `namespace: default` in all-namespaces/kustomization.yaml would achieve the same

**Comment by idlewis** [comment]
@leochr Yes, the purpose of the all-namespaces2 is to specify a different a namespace, and yes this could be done in all-namespaces. However, the idea was that, because all-namespaces adds in a new resource file (the cluster roles yaml) I was expecting that users would want to treat all-namespaces as a base to build on, and probably would prefer to leave it untouched, rather than having to edit it. So all-namespaces2 is an example of how a user could build on all-namespaces without having to modify it.
If you think it is better to combine the two, I'm happy to do that.
I also will add a readme to explain it either way, once you are happy with the content.

**Comment by leochr** [comment]
Thanks @idlewis . It'll be good to separate the folders that customers should modify from the folders/files we provide (i.e. move _all-namespace2_ and _test-namespace_ under `examples`)

Suggest the following names for the folders:
watch-own-namespace
watch-another-namespace
watch-all-namespaces

**Review by leochr — COMMENTED** [review]
@idlewis Thanks for the update. If possible, it'll be good to have the examples directly under `daily` folder. This way that's the only folder customers would have to edit and also avoid accidentally modifying other folders directly under overlays. 

Maybe you are planning to add, it'll be good to have an example for watch-another-namespace.

**Comment by idlewis** [comment]
@leochr I think I've addressed all the review comments. Hopefully should be ready for review/merge.

**Review by leochr — APPROVED** [review]
@idlewis Looks good. Thanks.

**Pull request merged**
