### PR TITLE
Pipeline

### PR DESCRIPTION
**Pull request by mcurran-us**
**What this PR does / why we need it?**:

- Code changes to support running in OnePipeline
- 

**Does this PR introduce a user-facing change?**
- No

- [ ] User guide
- [ ] `CHANGELOG.md`

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Review by leochr — APPROVED** [review]
@mcurran-us Thank you! Looks good to me. But I am not too familiar with the internals of OnePipeline, so it might be good to get someone familiar with OnePipeline to review as well.

**Comment by mcurran-us** [comment]
@leochr Thank you.  I've asked Dave to also take a look.

**Comment by davco01a** [comment]
Looks good to me, not familiar with fyre-e2e.sh

**Comment by leochr** [comment]
Thanks for the review Dave. Merging.

**Pull request merged**
